import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import "./globals.css";
import { cn } from "@/lib/utils";
import Providers from "@/utils/Providers";
import { Toaster } from "@/components/ui/sonner";

const IBM_Plex = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-IBM_Plex",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={cn(IBM_Plex.className, "bg-black text-white")}>
          <Toaster />
          <Providers>{children}</Providers>
        </body>
      </html>
    </SessionProvider>
  );
}
